wine = read.csv("wine.csv")
str(wine)
summary(wine)
model = lm(Price ~ HarvestRain +WinterRain, data = wine)
summary(model)
teamRank = c(1,2,3,3,4,4,4,4,5,5)
wins2012 = c(94,88,95,88,93,94,98,97,93,94)
cor(teamRank, wins2012)
wins2013 = c(97,97,92,93,92,96,94,96,92,90)
cor(teamRank, wins2013)
climate = read.csv("climate_change.csv")
str(climate)
summary(climate)
model1 = lm(Temp ~ MEI +  CO2 +  CH4 + N2O +  CFC.11 + CFC.12 + TSI +Aerosols, data =climate)
summary(model1)
trainingdata = subset(climate,Year < 2007)
testingdata = subset(climate,Year > 2006)
model1 = lm(Temp ~ MEI +  CO2 +  CH4 + N2O +  CFC.11 + CFC.12 + TSI +Aerosols, data = trainingdata)
summary(model1)
cor(trainingdata)
cor(climate$MEI, climate$CFC.11)
cor(climate$CO2, climate$CFC.11)
cor(climate$CH4, climate$CFC.11)
cor(climate$CFC.12, climate$CFC.11)
trainingmodel = lm(Temp ~ MEI + N2O + TSI + Aerosols, data = trainingdata)
summary(trainingmodel)
newmodel = step(model1)
summary(newmodel)
prediction = predict(newmodel,newdata = testingdata)
SSE = sum((prediction - testingdata$Temp)^2)
SST = sum((mean(testingdata$Temp) - testingdata$Temp)^2)
R2 = 1 - SSE/SST
R2
