parole = read.csv("parole.csv")
summary(parole)
str(parole)
table(parole$violator)
table(parole$male)
table(parole$multiple.offenses)
table(parole$age)
table(parole$state)
table(parole$crime)
parolestate = as.factor(parole$state)
parolecrime = as.factor(parole$crime)
table(parolestate)
table(parole$state)
set.seed(144)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
summary(train)
str(train)
summary(test)
str(test)
set.seed(144)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
summary(train)
str(train)
summary(test)
str(test)
set.seed(140)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
summary(train)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
summary(train)
set.seed(144)
library(caTools)
split = sample.split(parole$violator, SplitRatio = 0.7)
train = subset(parole, split == TRUE)
test = subset(parole, split == FALSE)
Model = glm(violator ~ ., data = train, family = "binomial")
summary(Model)
Model$coefficients['multiple.offenses']
exp(Model$coefficients['multiple.offenses'][[1]])
str(Model)
summary(Model)
logit = Model$coefficients['(Intercept)'][[1]] + Model$coefficients['male'][[1]] + Model$coefficients['race'][[1]] * 1 + Model$coefficients['age'][[1]] * 50+ Model$coefficients['time.served'][[1]] * 3 + Model$coefficients['max.sentence'][[1]] * 12 + Model$coefficients['crime'][[1]]
logit
exp(logit)
1/(1+exp(-logit))
testprediction <- predict(model, newdata = test, type = 'response')
hist(testprediction)


