gerber = read.csv("gerber.csv")
summary(gerber)
str(gerber)
table(gerber$voting)
108696/ nrow(gerber)
table(gerber$neighbors, gerber$voting)
table(gerber$self, gerber$voting)
table(gerber$hawthorne, gerber$voting)
table(gerber$civicduty, gerber$voting)
logmodel = glm(voting ~ civicduty + hawthorne+self+neighbors, data = gerber, family = "binomial")
summary(logmodel)
predictLog = predict(logmodel, type="response")
table(gerber$voting, predictLog > 0.3)
(134513+51966)/ (134513+51966+100875+56730)
table(gerber$voting, predictLog > 0.5)
235388/(235388+108696)
install.packages("ROCR")
library(ROCR)
ROCRpred = prediction(predictLog, gerber$voting)
as.numeric(performance(ROCRpred, "auc")@y.values)

install.packages("rpart")
library(rpart)
install.packages("rpart.plot")
library(rpart.plot)
CARTmodel = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber)
prp(CARTmodel)
CARTmodel1 = rpart(voting ~ civicduty + hawthorne + self + neighbors, data=gerber, cp =0.0)
prp(CARTmodel1)
 CARTmodel2 = rpart(voting ~ civicduty + hawthorne + self + neighbors+sex, data=gerber, cp = 0.0)
prp(CARTmodel2)
cartcontrol = rpart(voting ~ control, data=gerber, cp=0.0)
cartcontrol1 = rpart(voting ~ control+sex, data=gerber, cp=0.0)
prp(cartcontrol, digits=6)
prp(cartconrol1, digits = 6)
controlmodel = glm(voting~control+sex, data=gerber, family = "binomial")
summary(controlmodel)
Possibilities = data.frame(sex=c(0,0,1,1),control=c(0,1,0,1))
predict(controlmodel, newdata=Possibilities, type="response")
controlmodel1 = glm(voting~control+sex+sex:control, data=gerber, family = "binomial")
summary(controlmodel1)
predict(controlmodel1, newdata=Possibilities, type="response")
