airlines = read.csv("AirlinesCluster.csv")
summary(airlines)
install.packages("caret")
library(caret)
preproc = preProcess(airlines)
airlinesNorm = predict(preproc, airlines)
summary(airlinesNorm)
airlinesDist = dist(airlinesNorm, method = "euclidean")
airlinesclust = hclust(airlinesDist, method = "ward.D")
plot(airlinesclust)
airline = cutree(airlinesclust, k=5)
table(airline)
lapply(split(airlines, airline), colMeans)
 set.seed(88)
 kmeansclust = kmeans(airlinesNorm, centers=5, iter.max=1000)
 table(kmeansclust$cluster)
