hist(WHO$CellularSubscribers)
boxplot(WHO$CellularSubscribers)
boxplot(WHO$LifeExpectancy)
boxplot(WHO$LifeExpectancy ~ WHO$Region)
boxplot(WHO$LifeExpectancy ~ WHO$Region, xlab = "", ylab = "Life Expectancy", main = "Life Expectancy of Countries by Region")
table(WHO$Region)